//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xlRcode.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\R\\R-4.0.2")]
        public string RHome {
            get {
                return ((string)(this["RHome"]));
            }
            set {
                this["RHome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\R\\R-4.0.2\\bin\\x64")]
        public string RPath {
            get {
                return ((string)(this["RPath"]));
            }
            set {
                this["RPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int ConsoleLineLimit {
            get {
                return ((int)(this["ConsoleLineLimit"]));
            }
            set {
                this["ConsoleLineLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Eduardo\\Google Drive\\Meus Projetos\\xlRcode\\VS\\xlRcode\\InitializationCode" +
            ".txt")]
        public string InitializationCodeFile {
            get {
                return ((string)(this["InitializationCodeFile"]));
            }
            set {
                this["InitializationCodeFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Eduardo\\Google Drive\\Meus Projetos\\xlRcode\\VS\\xlRcode\\Functions")]
        public string FunctionsFolder {
            get {
                return ((string)(this["FunctionsFolder"]));
            }
            set {
                this["FunctionsFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://cloud.r-project.org/")]
        public string CRANMirror {
            get {
                return ((string)(this["CRANMirror"]));
            }
            set {
                this["CRANMirror"] = value;
            }
        }
    }
}
